# frozen_string_literal: true

module Superthread
  module Cli
    # Generate shell completion scripts for bash, zsh, and fish.
    # Uses Thor introspection to automatically discover commands and options.
    class Completion < Base
      desc "bash", "Generate bash completion script"
      long_desc <<~DESC
        Generate the autocompletion script for the bash shell.

        To load completions in your current shell session:

          source <(suth completion bash)

        To load completions for every new session, execute once:

          # macOS (Homebrew):
          suth completion bash > $(brew --prefix)/etc/bash_completion.d/suth

          # Linux:
          suth completion bash > /etc/bash_completion.d/suth

        You will need to start a new shell for this setup to take effect.
      DESC
      def bash
        puts bash_completion_script
      end

      desc "zsh", "Generate zsh completion script"
      long_desc <<~DESC
        Generate the autocompletion script for the zsh shell.

        To load completions in your current shell session:

          source <(suth completion zsh)

        To load completions for every new session, execute once:

          # macOS (Homebrew):
          suth completion zsh > $(brew --prefix)/share/zsh/site-functions/_suth

          # Linux:
          suth completion zsh > "${fpath[1]}/_suth"

        You will need to start a new shell for this setup to take effect.
      DESC
      def zsh
        puts zsh_completion_script
      end

      desc "fish", "Generate fish completion script"
      long_desc <<~DESC
        Generate the autocompletion script for the fish shell.

        To load completions in your current shell session:

          suth completion fish | source

        To load completions for every new session, execute once:

          suth completion fish > ~/.config/fish/completions/suth.fish

        You will need to start a new shell for this setup to take effect.
      DESC
      def fish
        puts fish_completion_script
      end

      private

      # Introspect Thor to get command structure
      def command_structure
        @command_structure ||= build_command_structure
      end

      def build_command_structure
        structure = {}
        main_class = Superthread::Cli::Main

        main_class.commands.each do |name, command|
          next if name == "help"

          structure[name] = {
            desc: command.description,
            subcommands: {},
            options: extract_options(command)
          }
        end

        # Add subcommand details
        main_class.subcommand_classes.each do |name, klass|
          next unless structure[name]

          klass.commands.each do |subcmd_name, subcmd|
            next if subcmd_name == "help"

            structure[name][:subcommands][subcmd_name] = {
              desc: subcmd.description,
              options: extract_options(subcmd)
            }
          end
        end

        structure
      end

      def extract_options(command)
        command.options.map do |name, opt|
          flag = "--#{name.to_s.tr("_", "-")}"
          flag = "-#{opt.aliases.first}, #{flag}" if opt.aliases&.any?
          {flag: flag, name: name.to_s.tr("_", "-"), desc: opt.description || name.to_s}
        end
      end

      def global_options
        [
          {flag: "-v, --verbose", name: "verbose", desc: "Detailed logging"},
          {flag: "-q, --quiet", name: "quiet", desc: "Minimal logging"},
          {flag: "-w, --workspace", name: "workspace", desc: "Workspace (ID or name)"},
          {flag: "--json", name: "json", desc: "Output as JSON"},
          {flag: "-a, --account", name: "account", desc: "Use specific account"},
          {flag: "-y, --yes", name: "yes", desc: "Auto-confirm prompts"}
        ]
      end

      def bash_completion_script
        cmds = command_structure
        main_commands = cmds.keys.join(" ")
        global_opts = global_options.map { |o| o[:flag].split(", ").last }.join(" ")

        subcommand_cases = cmds.map do |cmd, data|
          next if data[:subcommands].empty?

          subcmds = data[:subcommands].keys.join(" ")
          <<~CASE.chomp
            #{cmd})
                COMPREPLY=($(compgen -W "#{subcmds}" -- "${cur}"))
                return 0
                ;;
          CASE
        end.compact.join("\n")

        <<~BASH
          # Bash completion for suth (Superthread CLI)
          # Generated by: suth completion bash

          _suth() {
              local cur prev commands
              COMPREPLY=()
              cur="${COMP_WORDS[COMP_CWORD]}"
              prev="${COMP_WORDS[COMP_CWORD-1]}"

              commands="#{main_commands}"

              case "${prev}" in
                  suth)
                      COMPREPLY=($(compgen -W "${commands}" -- "${cur}"))
                      return 0
                      ;;
          #{subcommand_cases}
              esac

              # Complete options
              if [[ "${cur}" == -* ]]; then
                  COMPREPLY=($(compgen -W "#{global_opts}" -- "${cur}"))
                  return 0
              fi
          }

          complete -F _suth suth
        BASH
      end

      def zsh_completion_script
        cmds = command_structure

        commands_list = cmds.map do |cmd, data|
          "    '#{cmd}:#{escape_zsh(data[:desc])}'"
        end.join("\n")

        subcommand_cases = cmds.map do |cmd, data|
          next if data[:subcommands].empty?

          subcmds_list = data[:subcommands].map do |subcmd, subcmd_data|
            "        '#{subcmd}:#{escape_zsh(subcmd_data[:desc])}'"
          end.join("\n")

          <<~CASE.chomp
                    #{cmd})
                        local -a subcommands
                        subcommands=(
            #{subcmds_list}
                        )
                        _describe -t commands '#{cmd} subcommands' subcommands
                        ;;
          CASE
        end.compact.join("\n")

        <<~ZSH
          #compdef suth

          # Zsh completion for suth (Superthread CLI)
          # Generated by: suth completion zsh

          _suth() {
              local -a commands

              commands=(
          #{commands_list}
              )

              if (( CURRENT == 2 )); then
                  _describe 'command' commands
                  return
              fi

              case "${words[2]}" in
          #{subcommand_cases}
              esac
          }

          _suth "$@"
        ZSH
      end

      def fish_completion_script
        cmds = command_structure

        lines = [
          "# Fish completion for suth (Superthread CLI)",
          "# Generated by: suth completion fish",
          "",
          "# Disable file completion by default",
          "complete -c suth -f",
          "",
          "# Main commands"
        ]

        cmds.each do |cmd, data|
          lines << "complete -c suth -n __fish_use_subcommand -a #{cmd} -d '#{escape_fish(data[:desc])}'"
        end

        lines << ""

        cmds.each do |cmd, data|
          next if data[:subcommands].empty?

          lines << "# #{cmd} subcommands"
          data[:subcommands].each do |subcmd, subcmd_data|
            lines << "complete -c suth -n '__fish_seen_subcommand_from #{cmd}' -a #{subcmd} -d '#{escape_fish(subcmd_data[:desc])}'"
          end
          lines << ""
        end

        lines.join("\n")
      end

      def escape_zsh(str)
        str.to_s.gsub("'", "'\\''")
      end

      def escape_fish(str)
        str.to_s.gsub("'", "\\\\'")
      end
    end
  end
end
